"""empty message

Revision ID: 0f484a953a86
Revises: 155c814cff87
Create Date: 2018-12-23 02:35:09.837039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f484a953a86'
down_revision = '155c814cff87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_ibfk_3', 'comments', type_='foreignkey')
    op.drop_column('comments', 'role_id')
    op.drop_constraint('post_tags_ibfk_3', 'post_tags', type_='foreignkey')
    op.drop_column('post_tags', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_tags', sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('post_tags_ibfk_3', 'post_tags', 'roles', ['role_id'], ['id'])
    op.add_column('comments', sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_ibfk_3', 'comments', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
