"""empty message

Revision ID: 1028583a24f4
Revises: e5d6c1598c1d
Create Date: 2018-12-23 06:16:44.334517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1028583a24f4'
down_revision = 'e5d6c1598c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('role_for_comment', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('role_ids', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_ids'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_ids')
    op.drop_column('comments', 'role_for_comment')
    # ### end Alembic commands ###
