"""empty message

Revision ID: 155c814cff87
Revises: f321d8ed00fa
Create Date: 2018-12-23 02:17:22.517615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155c814cff87'
down_revision = 'f321d8ed00fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'roles', ['role_id'], ['id'])
    op.add_column('post_tags', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post_tags', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.drop_column('post_tags', 'role_id')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'role_id')
    # ### end Alembic commands ###
