"""empty message

Revision ID: 2e3a55a8a3b9
Revises: af96a204fa98
Create Date: 2018-12-23 05:41:36.286060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3a55a8a3b9'
down_revision = 'af96a204fa98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('role_for_comment', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'role_for_comment')
    # ### end Alembic commands ###
