"""empty message

Revision ID: 50ccd8e78a7f
Revises: 6c5acbcfdfb9
Create Date: 2018-12-23 06:11:20.214356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50ccd8e78a7f'
down_revision = '6c5acbcfdfb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'role_for_comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('role_for_comment', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
