"""empty message

Revision ID: 6c5acbcfdfb9
Revises: 2e3a55a8a3b9
Create Date: 2018-12-23 05:58:26.002116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c5acbcfdfb9'
down_revision = '2e3a55a8a3b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_ibfk_3', 'comments', type_='foreignkey')
    op.drop_column('comments', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_ibfk_3', 'comments', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
