"""empty message

Revision ID: 7654438ecdd4
Revises: bdcf6097b907
Create Date: 2018-12-23 00:46:51.578097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7654438ecdd4'
down_revision = 'bdcf6097b907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('social_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'users', ['social_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'social_id')
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###
