"""empty message

Revision ID: 7f3c0a576da3
Revises: 87fcf0c558f3
Create Date: 2018-12-23 01:26:27.756696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3c0a576da3'
down_revision = '87fcf0c558f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('roles', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'roles', 'roles', ['user_id'], ['id'])
    op.create_foreign_key(None, 'roles', 'users', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'user_id')
    op.drop_column('roles', 'role_id')
    # ### end Alembic commands ###
