"""empty message

Revision ID: 8583a0167e5e
Revises: 1028583a24f4
Create Date: 2018-12-23 06:19:02.476747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8583a0167e5e'
down_revision = '1028583a24f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'role_id')
    # ### end Alembic commands ###
