"""empty message

Revision ID: 860b168a24c4
Revises: cb4e69d320f5
Create Date: 2018-12-23 05:06:15.533108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '860b168a24c4'
down_revision = 'cb4e69d320f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_ids', sa.Integer(), nullable=True))
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_ids'], ['id'])
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_ibfk_1', 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'role_ids')
    # ### end Alembic commands ###
