"""empty message

Revision ID: 87fcf0c558f3
Revises: 7654438ecdd4
Create Date: 2018-12-23 01:22:01.077986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87fcf0c558f3'
down_revision = '7654438ecdd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['role_id'], ['id'])
    op.create_foreign_key(None, 'users', 'roles', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'user_id')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###
