"""empty message

Revision ID: af96a204fa98
Revises: 9f6c69b7933d
Create Date: 2018-12-23 05:15:12.807773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af96a204fa98'
down_revision = '9f6c69b7933d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_ids', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_ids'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_ids')
    # ### end Alembic commands ###
