"""empty message

Revision ID: b9c6e3fff345
Revises: 8583a0167e5e
Create Date: 2018-12-23 06:32:20.401273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9c6e3fff345'
down_revision = '8583a0167e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_ibfk_5', 'comments', type_='foreignkey')
    op.drop_column('comments', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_ibfk_5', 'comments', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
