"""empty message

Revision ID: bdcf6097b907
Revises: 9334eaf37f92
Create Date: 2018-12-16 18:26:24.344049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdcf6097b907'
down_revision = '9334eaf37f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tags', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'post_id')
    # ### end Alembic commands ###
