"""empty message

Revision ID: dab92fe3e407
Revises: 06c97e8a3171
Create Date: 2018-12-23 02:50:17.669630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dab92fe3e407'
down_revision = '06c97e8a3171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_tags_ibfk_3', 'post_tags', type_='foreignkey')
    op.drop_column('post_tags', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_tags', sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('post_tags_ibfk_3', 'post_tags', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
