"""empty message

Revision ID: f533fcb762fc
Revises: dab92fe3e407
Create Date: 2018-12-23 03:15:05.692619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f533fcb762fc'
down_revision = 'dab92fe3e407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_ibfk_2', 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_ibfk_2', 'comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
